spring:
  datasource:
    url: jdbc:h2:~/data/study.restauarnt
    database-platform: org.hibernate.dialect.H2Dialect
    username: sa
    password:
  h2:
    console:
      #기본설정 무시
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test